version: '3.9'
services:
  web:
    image: book_2
    build: ./
    command: [ "python", "manage.py", "runserver", "0.0.0.0:2001" ]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    restart: unless-stopped
    networks:
      default:
        aliases:
          - web
    depends_on:
      - dbb2
    ports:
      - "2001:2001"

  dbb2:
    image: postgres:latest
    ports:
      - "2032:5432"
    environment:
      - POSTGRES_DB=booqs20
      - POSTGRES_USER=booqs20
      - POSTGRES_PASSWORD=booqs20
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      default:
        aliases:
          - dbb2

  nginx:
    build: ./nginx
    volumes:
      - ./public:/app/public
    ports:
      - 2000:80
    depends_on:
      - web
