version: '3.9'
services:
  web:
    image: dj_boox
    build: ./
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8080" ]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    restart: unless-stopped
    networks:
      default:
        aliases:
          - expenses
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=expenses
      - POSTGRES_USER=expenses
      - POSTGRES_PASSWORD=DANub4rH7jx8jgDpsUNSVrQk
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      default:
        aliases:
          - postgres

  nginx:
    build: ./nginx
    volumes:
      - ./public:/app/public
    ports:
      - 8000:80
    depends_on:
      - web
